### ISSUE TITLE
Better api

### ISSUE THREAD

**Issue by KeizerDev** [G-S2h/rhythmbox-pleer#3]
I'm seeing that pleer is very slow atm. May implementing this `http://pleer.com/browser-extension/search?q=string` is faster!

**Comment by G-S2h** [comment]
Ok, I've set that up but it still needs some improvements.
Thank you, I didn't know about this API.

**Comment by KeizerDev** [comment]
You should check this out: https://github.com/KeizerDev/Rhythmbox-Pleer
Op 10 jul. 2015 20:30 schreef "G-S2h" <notifications@github.com>:

**Comment by KeizerDev** [comment]
Just didn't know about forking when I made that..

**Comment by G-S2h** [comment]
Ok so I'll probably just work with your repository from now on. Also, as you may see there are lines that need to be removed from your fork (since they are useless with the new API implementation).

**Comment by KeizerDev** [comment]
Ah okay, I will add you as a contributor
